version: '2.3'

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=church_db
    networks:
      - main
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "wait-for postgres:5432 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn church_project.wsgi -b 0.0.0.0:8000"
    container_name: app
    depends_on:
      - postgres
    expose:
      - "8000"
    hostname: app
    image: app-image
    networks:
      - main
    restart: on-failure

networks:
  main:

volumes:
  postgresql-data: