# Generated by Django 3.0.3 on 2021-01-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
