# Generated by Django 3.0.3 on 2020-07-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministry',
            old_name='contact_info',
            new_name='contact_information',
        ),
    ]
