# Generated by Django 3.0.3 on 2020-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20191025_1852'),
        ('ministries', '0003_ministry_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='ministries', to='schedule.Event'),
        ),
    ]
